### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/expo#1]
cc @nicko170

- [x] Code Review
- [ ] Add to website
- [x] Create packagist package
- [x] Github actions
- [x] Style CI
- [ ] Scrutinizer 
- [x] Add badges

**Comment by mabdullahsari** [comment]
Hey @atymic 

Any reason why it's still WIP? Gone off the radar perhaps?

**Comment by nicko170** [comment]
I ended up just having too many issues with Expo Notifications and was already collecting the APNs and GCM tokens so just moved to using them instead :-(

**Comment by mabdullahsari** [comment]
> I ended up just having too many issues with Expo Notifications and was already collecting the APNs and GCM tokens so just moved to using them instead :-(

That's a bummer. IIRC they reworked the Notifications system though (old one is called LegacyNotifications now). So I'd assume it to be much more robust nowadays.

I'll do some testing myself first if it really works as they promise on their docs.

But I guess you don't have any incentive now to continue maintaining this repo, now so would you be willing to move ownership, @nicko170?

**Comment by nicko170** [comment]
> > I ended up just having too many issues with Expo Notifications and was already collecting the APNs and GCM tokens so just moved to using them instead :-(
> 
> 
> 
> That's a bummer. IIRC they reworked the Notifications system though (old one is called LegacyNotifications now). So I'd assume it to be much more robust nowadays.
> 
> 
> 
> I'll do some testing myself first if it really works as they promise on their docs.
> 
> 
> 
> But I guess you don't have any incentive now to continue maintaining this repo, now so would you be willing to move ownership, @nicko170?

Yep, I am happy for you to take ownership / collab on it. 

I might look back into it at some stage, but part way through a dart / flutter re-write so probably not depending how that goes!

**Comment by mabdullahsari** [comment]
> Yep, I am happy for you to take ownership / collab on it.
> 
> I might look back into it at some stage, but part way through a dart / flutter re-write so probably not depending how that goes!

A'ight, cool. That sounds like a plan. 
I'll try taking a look at Expo Notifications this week.

How'd you like to proceed further with the transition? Any communication medium I can reach you on?

I'm not in a hurry, so take your time and enjoy the sun 🙂

Thanks for the quick replies. 🤘

**Comment by mabdullahsari** [comment]
Hey man @nicko170 👋🏼

Just got time to look at this, sorry. The new notification system works really well.
So I'd definitely want to collab / take ownership if it's still fine for you.

How'd you like to proceed further? Can I reach you somewhere?

Thanks!!

**Comment by dwightwatson** [comment]
Hey @atymic - looking to start using this in production and this could do with some bug fixes and support for Laravel 11. Would you mind adding me as a maintainer?

(I also look after the AWS SNS, FCM and APNS channels).

**Comment by mabdullahsari** [comment]
> Hey @atymic - looking to start using this in production and this could do with some bug fixes and support for Laravel 11. Would you mind adding me as a maintainer?
> 
> (I also look after the AWS SNS, FCM and APNS channels).

Hey @dwightwatson 

I've tried getting in touch with @atymic many times before, but unfortunately haven't received any replies. We have already created a—in my opinion—very decent implementation [in this repository here](https://github.com/dive-be/laravel-expo-channel). It'd be a bummer if you had to carry out this work twice because it already has support for PHP 8.3, Laravel 11, an extensive test suite, good documentation etc.

If you can get in touch with him, I'd be happy to hand over ownership for this piece of code that has been lingering in darkness!

**Comment by atymic** [comment]
@dwightwatson I've added you as a repo maintainer.

@mabdullahsari If you'd like to work with @dwightwatson to launch the channel you're welcome to. The person who originally created the channel is the one responsible for maintaining it.

**Comment by atymic** [comment]
@mabdullahsari your implementation looks good, so if you'd like move it here and release a new major version you can discuss with @dwightwatson

**Comment by dwightwatson** [comment]
Cool, your implementation looks a lot more fleshed out and would be great to have under this namespace. If you're open to PRing it into this repo and we can continue maintenance here let's do that.

**Comment by mabdullahsari** [comment]
> @mabdullahsari If you'd like to work with @dwightwatson to launch the channel you're welcome to. The person who originally created the channel is the one responsible for maintaining it.

Thanks!

---

> Cool, your implementation looks a lot more fleshed out and would be great to have under this namespace. If you're open to PRing it into this repo and we can continue maintenance here let's do that.

Hey 👋

Awesome! I'll make sure to submit a PR as soon as possible.

**Comment by dwightwatson** [comment]
@atymic could you please also add @mabdullahsari as a repo maintainer as they've graciously PR'd their work in?

**Comment by atymic** [comment]
Added you @mabdullahsari  :)

Thanks both
