### ISSUE TITLE
Can we tag a new 1.x release?

### ISSUE THREAD

**Issue by lnpbk** [laravel-notification-channels/expo#13]
Currently stuck on an older Laravel version, but would like the fix from `f99ae76e071b7911e97a8360bfd1affd6a8eb4f6`.

Could we release a 1.3.1?

**Comment by dwightwatson** [comment]
Yeah no worries, tagged 1.3.1 just for you 😄

**Comment by lnpbk** [comment]
I'm honoured 😂 Much appreciated!
