### ISSUE TITLE
Laravel 11 Supports 8.2 but this package version 2.0 does not

### ISSUE THREAD

**Issue by LuizCristino** [laravel-notification-channels/expo#16]
Want to know if it is possible to reduce the PHP min version from 8.3 to 8.2.

Laravel 11 still supports php 8.2 and the docker images that we use are currently using are using 8.2

**Comment by dwightwatson** [comment]
Hey Luiz, I get your point. We merged in 2.x from a community project and it was a total replacement of the previous version. 

I opened a PR to [test support against PHP 8.2](https://github.com/laravel-notification-channels/expo/pull/17) but it looks like we use syntax that isn't compatible. I don't think it's worth the effort of backdating all that code to support PHP 8.2 especially when that version will lose active support in 5 months.

If upgrading to 8.3 is out of scope for you I'd suggest sticking to 1.x of this package, or forking 2.x to temporarily revert the incompatible syntax.

Hope this makes sense and you understand where I'm coming from.
