### ISSUE TITLE
Update Guzzle dependency

### ISSUE THREAD

**Issue by jeffreyvanhees** [laravel-notification-channels/expo#3]
Cool package! Thanks for creating it! I tried to install it in my Laravel project. Unfortunately, the package is not compatible with the latest Guzzle version which Laravel uses.

``` - Root composer.json requires laravel-notification-channels/expo dev-main -> satisfiable by laravel-notification-channels/expo[dev-main].

- laravel-notification-channels/expo dev-main requires guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.3.1).
```
Might be good to take care of this before the official release of your package.

Keep up the good work! 

Edit: I'll do some testing with v7 and create a PR for it.Then you can decide for yourself if you do something with it.

**Comment by atymic** [comment]
Should be an easy upgrade, since the package doesn't use any advanced guzzle features. Feel free to PR :)
